//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BitstampTrader.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class MinMaxLog
    {
        public System.DateTime Day { get; set; }
        public decimal Minimum { get; set; }
        public decimal Maximum { get; set; }
        public string Currency { get; set; }
    }
}
