//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BitstampTrader.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int Id { get; set; }
        public decimal BuyAmount { get; set; }
        public Nullable<System.DateTime> BuyTimestamp { get; set; }
        public decimal BuyPrice { get; set; }
        public Nullable<decimal> BuyValue { get; set; }
        public Nullable<decimal> BuyFee { get; set; }
        public long BuyId { get; set; }
        public Nullable<decimal> SellAmount { get; set; }
        public Nullable<System.DateTime> SellTimestamp { get; set; }
        public Nullable<decimal> SellPrice { get; set; }
        public Nullable<decimal> SellValue { get; set; }
        public Nullable<decimal> SellFee { get; set; }
        public Nullable<long> SellId { get; set; }
        public string Currency { get; set; }
    }
}
